app = "fmu-gateway"
primary_region = "lhr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[env]]
  DATABASE_URL = ""
  STRIPE_SECRET_KEY = ""
  REDIS_URL = "redis://localhost:6379"